# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Azeem Ansar
tagline:          Azeem Ansar
url:              http://azeemansar.com
paginate:         1
baseurl:          /
author:
  name:           Azeem Ansar
  url:              azeem.ansar@gmail.com
  email:          azeem.ansar@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/azeemansar/azeemansar.github.io
